var ques_stack_vn = [
{img: "valhein1", name: "Valhein là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "valhein1", name: "Valhein là một Pháp sư?", anleft: 0, anright: 1, star: 0},
{img: "valhein8", name: "Nội tại Valhein có hiệu ứng đặc biệt ở đòn thứ 3?", anleft: 1, anright: 0, star: 1},
{img: "valhein8", name: "Nội tại Valhein không đổi màu Phi tiêu?", anleft: 0, anright: 1, star: 1},
{img: "valhein2", name: "Chiêu cuối Valhein giúp tăng tốc độ chạy?", anleft: 1, anright: 0, star: 1},
{img: "valhein2", name: "Chiêu cuối Valhein không tăng tốc đánh?", anleft: 0, anright: 1, star: 1},
{img: "valhein2", name: "Chiêu cuối Valhein có 5 viên đạn?", anleft: 0, anright: 1, star: 1},
{img: "valhein2", name: "Chiêu cuối Valhein sát thương như nhau từ viên 2?", anleft: 0, anright: 1, star: 1},
{img: "valhein3", name: "Vũ Khí Tối Thượng không là skin của Valhein?", anleft: 0, anright: 1, star: 0},
{img: "valhein4", name: "Đại Công Tước là skin của Valhein?", anleft: 1, anright: 0, star: 0},
{img: "valhein5", name: "Quang Vinh là skin của Valhein?", anleft: 1, anright: 0, star: 0},
{img: "valhein6", name: "Số 7 Thần Sầu không là skin của Valhein?", anleft: 0, anright: 1, star: 0},
{img: "thane1", name: "Thane là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "thane1", name: "Thane là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "thane1", name: "Thane là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "thane4", name: "Nội tại Thane giúp hồi máu?", anleft: 1, anright: 0, star: 1},
{img: "thane4", name: "Nội tại Thane hồi máu khi mất máu?", anleft: 0, anright: 1, star: 1},
{img: "thane3", name: "Chiêu cuối Thane có thể bị hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "thane3", name: "Chiêu cuối Thane miễn thương khi đang dùng?", anleft: 1, anright: 0, star: 1},
{img: "thane3", name: "Chiêu cuối Thane có gây Sát thương chuẩn?", anleft: 1, anright: 0, star: 1},
{img: "thane5", name: "Quang Vinh không là skin của Thane?", anleft: 0, anright: 1, star: 0},
{img: "veera1", name: "Veera là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "veera1", name: "Veera là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "veera6", name: "Nội tại Veera giảm giáp phép mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "veera6", name: "Nội tại Veera không giảm hồi các chiêu khi phụ hạ?", anleft: 0, anright: 1, star: 1},
{img: "veera2", name: "Chiêu cuối Veera có 5 lượt tấn công?", anleft: 1, anright: 0, star: 1},
{img: "veera2", name: "Chiêu cuối Veera có thể tấn công nhiều mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "veera2", name: "Chiêu cuối Veera sát thương như nhau từ lượt 2?", anleft: 0, anright: 1, star: 1},
{img: "veera2", name: "Không thể né được bởi Chiêu cuối Veera?", anleft: 0, anright: 1, star: 1},
{img: "veera4", name: "Nàng Dơi Tuyết không là skin của Veera?", anleft: 0, anright: 1, star: 0},
{img: "veera5", name: "Y Tá Bạo Loạn là skin của Veera?", anleft: 1, anright: 0, star: 0},
{img: "lubo1", name: "Lữ Bố là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "lubo1", name: "Lữ Bố là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "lubo7", name: "Nội tại Lữ Bố giảm hồi chiêu kỹ năng khác?", anleft: 1, anright: 0, star: 1},
{img: "lubo7", name: "Nội tại Lữ Bố chỉ kích hoạt khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "lubo3", name: "Chiêu cuối Lữ Bố tự hồi máu khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "lubo3", name: "Chiêu cuối Lữ Bố hồi máu trên đòn đánh?", anleft: 1, anright: 0, star: 1},
{img: "lubo3", name: "Chiêu cuối Lữ Bố không kháng hiệu ứng?", anleft: 0, anright: 1, star: 1},
{img: "lubo4", name: "Đặc Nhiệm SWAT là skin của Lữ Bố?", anleft: 1, anright: 0, star: 0},
{img: "lubo5", name: "Tiệc Bãi Biển không là skin của Lữ Bố?", anleft: 0, anright: 1, star: 0},
{img: "mina1", name: "Mina là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "mina1", name: "Mina là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "mina4", name: "Nội tại Mina kích hoạt khi chịu sát thương?", anleft: 1, anright: 0, star: 1},
{img: "mina4", name: "Nội tại Mina kích hoạt khi ở cạnh đồng đội?", anleft: 0, anright: 1, star: 1},
{img: "mina2", name: "Chiêu cuối Mina khiến địch tấn công cô?", anleft: 1, anright: 0, star: 1},
{img: "mina2", name: "Mina miễn thương khi dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "mina2", name: "Tất cả địch chỉ tấn công Mina bởi Chiêu cuối?", anleft: 1, anright: 0, star: 1},
{img: "mina5", name: "Tiệc Bánh Kẹo là skin của Mina?", anleft: 1, anright: 0, star: 0},
{img: "krixi1", name: "Krixi là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "krixi1", name: "Krixi là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "krixi6", name: "Nội tại Krixi tăng tốc chạy khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "krixi6", name: "Kĩ năng trúng đích kích hoạt Nội tại Krixi?", anleft: 1, anright: 0, star: 1},
{img: "krixi3", name: "Chiêu cuối Krixi giúp đồng đội tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "krixi3", name: "Chiêu cuối Krixi chỉ dùng khi có mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "krixi3", name: "Chiêu cuối Krixi giúp cô tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "krixi3", name: "Không thể dùng Chiêu khác khi Krixi dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "krixi3", name: "Chiêu cuối Krixi có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "krixi4", name: "Tiệc Bãi Biển không là skin của Krixi?", anleft: 0, anright: 1, star: 0},
{img: "krixi5", name: "Cô Tiên Thỏ là skin của Krixi?", anleft: 1, anright: 0, star: 0},
{img: "mganga1", name: "Mganga là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "mganga1", name: "Mganga là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "mganga1", name: "Mganga là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "mganga5", name: "Nội tại Mganga có kèm hiệu ứng độc?", anleft: 1, anright: 0, star: 1},
{img: "mganga5", name: "Nội tại Mganga đánh thường không cộng Ấn tà thuật?", anleft: 0, anright: 1, star: 1},
{img: "mganga5", name: "Nội tại Mganga có tối đa 4 Ấn tà thuật?", anleft: 0, anright: 1, star: 1},
{img: "mganga4", name: "Chiêu cuối Mganga kích nổ Ấn tà thuật?", anleft: 1, anright: 0, star: 1},
{img: "mganga4", name: "Chiêu cuối Mganga không hồi máu cho đồng đội?", anleft: 0, anright: 1, star: 1},
{img: "mganga4", name: "Chiêu cuối Mganga chỉ gây thêm sát thương bởi dấu Ấn?", anleft: 0, anright: 1, star: 1},
{img: "mganga3", name: "Tiệc Bánh Kẹo không là skin của Mganga?", anleft: 0, anright: 1, star: 0},
{img: "trieuvan1", name: "Triệu Vân là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "trieuvan1", name: "Triệu Vân là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "trieuvan6", name: "Nội tại Triệu Vân giúp hồi máu tối đa?", anleft: 1, anright: 0, star: 1},
{img: "trieuvan6", name: "Nội tại Triệu Vân không tăng sát thương?", anleft: 0, anright: 1, star: 1},
{img: "trieuvan6", name: "Nội tại Triệu Vân chỉ kích hoạt khi hạ địch?", anleft: 0, anright: 1, star: 1},
{img: "trieuvan7", name: "Chiêu cuối Triệu Vân tấn công nhiều mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "trieuvan7", name: "Chiêu cuối Triệu Vân không hất tung mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "trieuvan7", name: "Chiêu cuối Triệu Vân giúp tăng miễn thương?", anleft: 1, anright: 0, star: 1},
{img: "trieuvan7", name: "Chiêu cuối Triệu Vân tăng sát thương đánh thường?", anleft: 1, anright: 0, star: 1},
{img: "trieuvan3", name: "Quang Vinh không là skin của Triệu Vân?", anleft: 0, anright: 1, star: 0},
{img: "trieuvan4", name: "Dũng Sĩ Đồ Long là skin của Triệu Vân?", anleft: 1, anright: 0, star: 0},
{img: "trieuvan8", name: "Quý Công Tử không là skin của Triệu Vân?", anleft: 0, anright: 1, star: 0},
{img: "omega1", name: "Omega là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "omega1", name: "Omega là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "omega4", name: "Nội tại Omega gây sát thương lên công trình?", anleft: 1, anright: 0, star: 1},
{img: "omega4", name: "Nội tại Omega không gây hiệu ứng lên công trình?", anleft: 0, anright: 1, star: 1},
{img: "omega2", name: "Chiêu cuối Omega có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "omega2", name: "Có thể đánh thường khi Omega dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "omega2", name: "Chiêu cuối Omega giúp tăng tốc chạy khi đứng cạnh?", anleft: 0, anright: 1, star: 1},
{img: "kahlii1", name: "Kahlii là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "kahlii1", name: "Kahlii là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "kahlii3", name: "Nội tại Kahlii gây hiệu ứng xuyên thấu?", anleft: 1, anright: 0, star: 1},
{img: "kahlii3", name: "Nội tại Kahlii xuyên thấu các mục tiêu xung quanh?", anleft: 0, anright: 1, star: 1},
{img: "kahlii2", name: "Chiêu cuối Kahlii có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "kahlii2", name: "Có thể đánh thường khi Kahlii dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "kahlii2", name: "Chiêu cuối Kahlii tấn công mục tiêu phía trước?", anleft: 1, anright: 0, star: 1},
{img: "kahlii2", name: "Chiêu cuối Kahlii không gây thêm sát thương lên quái?", anleft: 0, anright: 1, star: 1},
{img: "kahlii4", name: "Quàng Khăn Đỏ không là skin của Kahlii?", anleft: 0, anright: 1, star: 0},
{img: "kahlii5", name: "Cô Dâu Hắc Ám là skin của Kahlii?", anleft: 1, anright: 0, star: 0},
{img: "zephys1", name: "Zephys là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "zephys1", name: "Zephys là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "zephys5", name: "Nội tại Zephys giúp hồi máu?", anleft: 0, anright: 1, star: 1},
{img: "zephys5", name: "Nội tại Zephys tăng miễn thương khi mất máu?", anleft: 1, anright: 0, star: 1},
{img: "zephys2", name: "Chiêu cuối Zephys không thể bay qua tường?", anleft: 0, anright: 1, star: 1},
{img: "zephys2", name: "Chiêu cuối Zephys không thể hất văng mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "zephys2", name: "Chiêu cuối Zephys tăng sát thương lên địch trúng chiêu?", anleft: 1, anright: 0, star: 1},
{img: "zephys3", name: "Hiệp Sĩ Bí Ngô không là skin của Zephys?", anleft: 0, anright: 1, star: 0},
{img: "dieuthuyen1", name: "Điêu Thuyền là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "dieuthuyen1", name: "Điêu Thuyền là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "dieuthuyen5", name: "Chịu thêm sát thương bởi đóng băng Điêu Thuyền?", anleft: 1, anright: 0, star: 1},
{img: "dieuthuyen5", name: "Đóng băng không kích hoạt Nội tại Điêu Thuyền?", anleft: 0, anright: 1, star: 1},
{img: "dieuthuyen2", name: "Chiêu cuối Điêu Thuyền có thể hủy khi dùng?", anleft: 1, anright: 0, star: 1},
{img: "dieuthuyen2", name: "Chiêu cuối Điêu Thuyền có thể di chuyển khi dùng?", anleft: 0, anright: 1, star: 1},
{img: "dieuthuyen2", name: "Chiêu cuối Điêu Thuyền giúp tăng giáp?", anleft: 1, anright: 0, star: 1},
{img: "dieuthuyen2", name: "Chiêu cuối Điêu Thuyền có thể đóng băng địch?", anleft: 0, anright: 1, star: 1},
{img: "dieuthuyen3", name: "Tiệc Bãi Biển không là skin của Điêu Thuyền?", anleft: 0, anright: 1, star: 0},
{img: "dieuthuyen6", name: "Hoa Hậu là skin của Điêu Thuyền?", anleft: 1, anright: 0, star: 0},
{img: "chaugnar1", name: "Chaugnar là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "chaugnar1", name: "Chaugnar là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "chaugnar4", name: "Nội tại Chaugnar giúp tăng miễn thương?", anleft: 1, anright: 0, star: 1},
{img: "chaugnar4", name: "Nội tại Chaugnar không tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "chaugnar4", name: "Nội tại Chaugnar giúp hóa giải khống chế?", anleft: 1, anright: 0, star: 1},
{img: "chaugnar4", name: "Nội tại Chaugnar kích hoạt khi dùng kỹ năng?", anleft: 0, anright: 1, star: 1},
{img: "chaugnar2", name: "Chiêu cuối Chaugnar chỉ hóa giải khống chế bản thân?", anleft: 0, anright: 1, star: 1},
{img: "chaugnar2", name: "Chiêu cuối Chaugnar giúp đồng minh tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "chaugnar2", name: "Chiêu cuối Chaugnar không tăng miễn thương đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "chaugnar2", name: "Chiêu cuối Chaugnar giảm tốc chạy mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "chaugnar3", name: "Quang Vinh không là skin của Chaugnar?", anleft: 0, anright: 1, star: 0},
{img: "violet1", name: "Violet là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "violet1", name: "Violet là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "violet8", name: "Nội tại Violet giúp giảm hồi chiêu kỹ năng?", anleft: 1, anright: 0, star: 1},
{img: "violet8", name: "Nội tại Violet kích hoạt khi dùng kỹ năng?", anleft: 0, anright: 1, star: 1},
{img: "violet6", name: "Chiêu cuối Violet chỉ sát thương trên một mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "violet6", name: "Chiêu cuối Violet có thể tìm diệt mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "violet3", name: "Mèo Siêu Quậy là skin của Violet?", anleft: 1, anright: 0, star: 0},
{img: "violet4", name: "Phi Công Trẻ không là skin của Violet?", anleft: 0, anright: 1, star: 0},
{img: "violet5", name: "Tiệc Bãi Biển không là skin của Violet?", anleft: 0, anright: 1, star: 0},
{img: "butterfly1", name: "Butterfly là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "butterfly1", name: "Butterfly là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "butterfly3", name: "Nội tại Butterfly kích hoạt khi hạ hoặc phụ?", anleft: 1, anright: 0, star: 1},
{img: "butterfly3", name: "Nội tại Butterfly chỉ giúp làm mới Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "butterfly2", name: "Chiêu cuối Butterfly ám sát mục tiêu nhiều máu?", anleft: 0, anright: 1, star: 1},
{img: "butterfly2", name: "Chiêu cuối Butterfly không thể dùng lên quái?", anleft: 0, anright: 1, star: 1},
{img: "butterfly2", name: "Chiêu cuối Butterfly giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "butterfly2", name: "Chiêu cuối Butterfly giúp tăng miễn thương?", anleft: 1, anright: 0, star: 1},
{img: "butterfly2", name: "Chiêu cuối Butterfly hồi máu khi kết thúc mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "butterfly4", name: "Nữ Quái Nổi Loạn là skin của Butterfly?", anleft: 1, anright: 0, star: 0},
{img: "butterfly5", name: "Quận Chúa Đế Chế không là skin của Butterfly?", anleft: 0, anright: 1, star: 0},
{img: "butterfly6", name: "Teen Nữ Công Nghệ không là skin của Butterfly?", anleft: 0, anright: 1, star: 0},
{img: "ormarr1", name: "Ormarr là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "ormarr1", name: "Ormarr là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "ormarr1", name: "Ormarr là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "ormarr5", name: "Nội tại Ormarr kích hoạt khi gây sát thương?", anleft: 1, anright: 0, star: 1},
{img: "ormarr5", name: "Nội tại Ormarr nhất định làm choáng?", anleft: 0, anright: 1, star: 1},
{img: "ormarr2", name: "Chiêu cuối Ormarr có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "ormarr2", name: "Chiêu cuối Ormarr giảm tốc chạy mục tiêu trúng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "ormarr2", name: "Chiêu cuối Ormarr nhất định làm choáng mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "ormarr3", name: "Thông Thỏa Thích không là skin của Ormarr?", anleft: 0, anright: 1, star: 0},
{img: "ormarr4", name: "Giáo Viên Thể Hình là skin của Ormarr?", anleft: 1, anright: 0, star: 0},
{img: "azzenka1", name: "Azzen'Ka là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "azzenka1", name: "Azzen'Ka là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "azzenka1", name: "Azzen'Ka là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "azzenka3", name: "Nội tại Azzen'Ka có thể hóa đá mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "azzenka3", name: "Nội tại Azzen'Ka kích hoạt khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "azzenka3", name: "Nội tại Azzen'Ka có tỷ lệ hóa đá mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "azzenka3", name: "Nội tại Azzen'Ka hóa đá khi đủ 3 Lời nguyền?", anleft: 1, anright: 0, star: 1},
{img: "azzenka2", name: "Chiêu cuối Azzen'Ka làm chậm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "azzenka2", name: "Chiêu cuối Azzen'Ka giúp tăng tốc chạy đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "azzenka2", name: "Chiêu cuối Azzen'Ka hóa đá mục tiêu trúng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "alice1", name: "Alice là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "alice1", name: "Alice không là Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "alice3", name: "Nội tại giúp Alice tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "alice3", name: "Nội tại Alice giúp đồng đội tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "alice2", name: "Chiêu cuối Alice làm câm lặng đối thủ?", anleft: 1, anright: 0, star: 1},
{img: "alice2", name: "Giảm Tốc đánh khi dính Chiêu cuối Alice?", anleft: 0, anright: 1, star: 1},
{img: "alice2", name: "Chiêu cuối Alice giúp đồng đội tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "alice4", name: "Bé Gấu Tuyết là skin của Alice?", anleft: 1, anright: 0, star: 0},
{img: "gildur4", name: "Nội tại Gildur đẩy lùi mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "gildur4", name: "Nội tại Gildur không tạo lá chắn?", anleft: 0, anright: 1, star: 1},
{img: "gildur4", name: "Nội tại Gildur kích hoạt ở đòn đánh thường thứ 3?", anleft: 0, anright: 1, star: 1},
{img: "gildur1", name: "Gildur là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "gildur1", name: "Gildur có thể là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "gildur1", name: "Gildur không phải tướng Đỡ đòn?", anleft: 0, anright: 1, star: 0},
{img: "gildur2", name: "Gildur có thể hủy Chiêu cuối lúc đang bật?", anleft: 1, anright: 0, star: 1},
{img: "gildur2", name: "Chiêu cuối Gildur có thể làm choáng cả bên địch?", anleft: 1, anright: 0, star: 1},
{img: "gildur2", name: "Có thể hủy Chiêu cuối Gildur bằng làm choáng?", anleft: 1, anright: 0, star: 1},
{img: "gildur3", name: "Gildur có skin Tiệc Bãi Biển?", anleft: 1, anright: 0, star: 0},
{img: "yorn1", name: "Yorn là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "yorn1", name: "Yorn có thể là Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "yorn5", name: "Đòn đánh thường thứ 5 kích hoạt Nội tại Yorn?", anleft: 1, anright: 0, star: 1},
{img: "yorn5", name: "Nội tại Yorn công kích 1 mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "yorn2", name: "Chiêu cuối Yorn bắn mũi tên xuyên bản đồ?", anleft: 1, anright: 0, star: 1},
{img: "yorn2", name: "Chiêu cuối Yorn không sát thương lên quái?", anleft: 0, anright: 1, star: 1},
{img: "yorn2", name: "Chiêu cuối Yorn dừng lại khi trúng địch?", anleft: 1, anright: 0, star: 1},
{img: "yorn3", name: "Yorn có skin Đặc Nhiệm Swat?", anleft: 1, anright: 0, star: 0},
{img: "yorn4", name: "Thế Tử Nguyệt Tộc không là skin của Yorn?", anleft: 0, anright: 1, star: 0},
{img: "toro1", name: "Toro là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "toro1", name: "Toro là một tay Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "toro5", name: "Nội tại Toro miễn khống chế khi dùng chiêu?", anleft: 1, anright: 0, star: 1},
{img: "toro5", name: "Nội tại Toro không tăng miễn thương?", anleft: 0, anright: 1, star: 1},
{img: "toro2", name: "Chiêu cuối Toro giảm tốc chạy đối thủ?", anleft: 1, anright: 0, star: 1},
{img: "toro2", name: "Chiêu cuối Toro không thể hất tung địch?", anleft: 0, anright: 1, star: 1},
{img: "toro4", name: "Trung Phong Cắm không là skin của Toro?", anleft: 0, anright: 1, star: 0},
{img: "taara1", name: "Taara là một tay Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "taara1", name: "Taara có thể là Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "taara1", name: "Taara là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "taara5", name: "Nội tại Taara tăng sát thương khi mất máu?", anleft: 1, anright: 0, star: 1},
{img: "taara5", name: "Nội tại Taara không hồi máu khi dùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "taara2", name: "Chiêu cuối Taara tự động hồi máu?", anleft: 1, anright: 0, star: 1},
{img: "taara2", name: "Chiêu cuối Taara không tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "taara2", name: "Chiêu cuối Taara giúp đồng đội hồi máu?", anleft: 0, anright: 1, star: 1},
{img: "taara4", name: "Hỏa Ngọc Nữ Đế là skin của Taara?", anleft: 1, anright: 0, star: 0},
{img: "taara3", name: "Tiệc Bãi Biển không là skin của Taara?", anleft: 0, anright: 1, star: 0},
{img: "nakroth1", name: "Nakroth là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "nakroth1", name: "Nakroth có thể là Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "nakroth7", name: "Nội tại Nakroth hất tung địch ở đòn thứ 4?", anleft: 1, anright: 0, star: 1},
{img: "nakroth7", name: "Nội tại Nakroth có thể tăng tốc đánh?", anleft: 1, anright: 0, star: 1},
{img: "nakroth2", name: "Nakroth không bị khống chế khi dùng Chiêu cuối?", anleft: 1, anright: 0, star: 1},
{img: "nakroth2", name: "Chiêu cuối Nakroth không thể hất văng địch?", anleft: 0, anright: 1, star: 1},
{img: "nakroth4", name: "Bboy Công Nghệ không là skin của Nakroth?", anleft: 0, anright: 1, star: 0},
{img: "nakroth5", name: "Chiến Binh Hỏa Ngục là skin của Nakroth?", anleft: 1, anright: 0, star: 0},
{img: "nakroth6", name: "Siêu Việt Bậc I không là skin của Nakroth?", anleft: 0, anright: 1, star: 0},
{img: "grakk1", name: "Grakk là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "grakk1", name: "Grakk là một tay Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "grakk1", name: "Grakk có thể là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "grakk5", name: "Nội tại Grakk kích hoạt sau khi hy sinh?", anleft: 1, anright: 0, star: 1},
{img: "grakk6", name: "Chiêu cuối Grakk có thể hủy khi đang dùng?", anleft: 1, anright: 0, star: 1},
{img: "grakk6", name: "Chiêu cuối Grakk không thể đổi hướng?", anleft: 0, anright: 1, star: 1},
{img: "grakk6", name: "Chiêu cuối Grakk có tạo lá chắn?", anleft: 1, anright: 0, star: 1},
{img: "grakk3", name: "Chàng Gấu Tuyết không là skin của Grakk?", anleft: 0, anright: 1, star: 0},
{img: "grakk4", name: "Thuyền Trưởng Râu Đỏ là skin của Grakk?", anleft: 1, anright: 0, star: 0},
{img: "aleister1", name: "Aleister là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "aleister1", name: "Aleister là một Sát thủ chăng?", anleft: 0, anright: 1, star: 0},
{img: "aleister4", name: "Nội tại Aleister tăng sát thương với 3 điểm ma thuật?", anleft: 1, anright: 0, star: 1},
{img: "aleister2", name: "Chiêu cuối Aleister có thể hủy khi đang dùng?", anleft: 1, anright: 0, star: 1},
{img: "aleister2", name: "Có thể đánh thường khi dính Chiêu cuối Aleister?", anleft: 0, anright: 1, star: 1},
{img: "aleister3", name: "Quang Vinh không là skin của Aleister?", anleft: 0, anright: 1, star: 0},
{img: "fennik1", name: "Fennik là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "fennik1", name: "Dường như Fennik là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "fennik4", name: "Nội tại Fennik lan sát thương quanh mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "fennik2", name: "Chiêu cuối Fennik trói chân mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "fennik2", name: "Chiêu cuối Fennik giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "fennik2", name: "Tăng tốc chạy khi đi qua Chiêu cuối Fennik?", anleft: 0, anright: 1, star: 1},
{img: "fennik3", name: "Tuần Lộc Láu Lỉnh không là skin của Fennik?", anleft: 0, anright: 1, star: 0},
{img: "fennik5", name: "Tiệc Bánh Kẹo là skin của Fennik?", anleft: 1, anright: 0, star: 0},
{img: "lumburr1", name: "Lumburr là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "lumburr1", name: "Lumburr là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "lumburr1", name: "Lumburr là một Đấu sĩ?", anleft: 0, anright: 1, star: 0},
{img: "lumburr3", name: "Nội tại Lumburr tăng giáp cho tất cả đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "lumburr3", name: "Nội tại Lumburr kích hoạt khi có đồng đội bên cạnh?", anleft: 1, anright: 0, star: 1},
{img: "lumburr3", name: "Nội tại Lumburr tăng giáp cho đồng đội máu cao nhất?", anleft: 0, anright: 1, star: 1},
{img: "lumburr2", name: "Chiêu cuối Lumburr chỉ hất văng mục tiêu đầu tiên?", anleft: 0, anright: 1, star: 1},
{img: "lumburr2", name: "Chiêu cuối Lumburr làm chậm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "lumburr2", name: "Chiêu cuối Lumburr giúp tăng tốc chạy đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "lumburr2", name: "Chiêu cuối Lumburr sát thương địch trong vùng chiêu?", anleft: 1, anright: 0, star: 1},
{img: "natalya1", name: "Natalya là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "natalya1", name: "Natalya là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "natalya7", name: "Nội tại Natalya thêm sát thương khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "natalya7", name: "Nội tại Natalya có thể cộng dồn sát thương?", anleft: 1, anright: 0, star: 1},
{img: "natalya2", name: "Natalya có thể di chuyển lúc dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "natalya2", name: "Chiêu cuối Natalya có thể hủy khi đang dùng?", anleft: 1, anright: 0, star: 1},
{img: "natalya2", name: "Chiêu cuối Natalya có thể di chuyển đổi hướng?", anleft: 1, anright: 0, star: 1},
{img: "natalya2", name: "Chiêu cuối Natalya không giải khống chế khi dùng?", anleft: 0, anright: 1, star: 1},
{img: "natalya2", name: "Chiêu cuối Natalya giúp tạo lá chắn cho đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "natalya4", name: "Nghệ Nhân Lân không là skin của Natalya?", anleft: 0, anright: 1, star: 0},
{img: "natalya5", name: "Quà Quái Quỷ là skin của Natalya?", anleft: 1, anright: 0, star: 0},
{img: "natalya6", name: "Phó Nháy Nhí Nhảnh là skin của Natalya?", anleft: 1, anright: 0, star: 0},
{img: "cresht1", name: "Cresht là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "cresht1", name: "Cresht là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "cresht1", name: "Cresht là một Đấu sĩ?", anleft: 0, anright: 1, star: 0},
{img: "cresht4", name: "Nội tại Cresht tăng Nộ khi dùng kỹ năng?", anleft: 0, anright: 1, star: 1},
{img: "cresht4", name: "Nội tại Cresht có thể hóa Thủy thần bất cứ khi nào?", anleft: 0, anright: 1, star: 1},
{img: "cresht2", name: "Chiêu cuối Cresht kích hoạt khi nhận đủ Nộ?", anleft: 1, anright: 0, star: 1},
{img: "cresht2", name: "Chiêu cuối Cresht choáng mục tiêu đầu tiên trúng phải?", anleft: 0, anright: 1, star: 1},
{img: "cresht2", name: "Chiêu cuối Cresht tăng tốc chạy cho đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "cresht2", name: "Chiêu cuối Cresht tạo lớp bảo hộ cho đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "cresht3", name: "Cá Cắn Cáp không là skin của Cresht?", anleft: 0, anright: 1, star: 0},
{img: "jinna1", name: "Jinna là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "jinna1", name: "Jinna là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "jinna3", name: "Nội tại Jinna kích hoạt sau 4 lần công kích?", anleft: 1, anright: 0, star: 1},
{img: "jinna3", name: "Nội tại Jinna đánh thường không tích Ấn chú?", anleft: 0, anright: 1, star: 1},
{img: "jinna2", name: "Chiêu cuối Jinna giúp tăng miễn thương?", anleft: 1, anright: 0, star: 1},
{img: "jinna2", name: "Chiêu cuối Jinna tăng miễn thương khi đồng đội bên cạnh?", anleft: 0, anright: 1, star: 1},
{img: "jinna2", name: "Chiêu cuối Jinna giúp đồng minh tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "jinna2", name: "Chiêu cuối Jinna có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "jinna4", name: "Dạ Xoa Vương không là skin của Jinna?", anleft: 0, anright: 1, star: 0},
{img: "payna1", name: "Payna là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "payna1", name: "Payna là một Pháp sư?", anleft: 0, anright: 1, star: 0},
{img: "payna4", name: "Nội tại Payna kích hoạt khi mục tiêu tấn công cô?", anleft: 1, anright: 0, star: 1},
{img: "payna4", name: "Nội tại Payna giảm tốc chạy toàn bộ mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "payna2", name: "Chiêu cuối Payna giúp tăng giáp đồng minh?", anleft: 1, anright: 0, star: 1},
{img: "payna2", name: "Chiêu cuối Payna hồi máu đồng đội trong vùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "payna2", name: "Chiêu cuối Payna giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "payna2", name: "Chiêu cuối Payna có thể choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "payna2", name: "Chiêu cuối Payna có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "payna2", name: "Chiêu cuối Payna không thể di chuyển khi dùng?", anleft: 0, anright: 1, star: 1},
{img: "maloch1", name: "Maloch là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "maloch1", name: "Maloch là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "maloch1", name: "Maloch là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "maloch4", name: "Nội tại Maloch kích hoạt khi Quỷ kiếm trúng địch?", anleft: 1, anright: 0, star: 1},
{img: "maloch4", name: "Nội tại Maloch không hồi máu tổn thất?", anleft: 0, anright: 1, star: 1},
{img: "maloch4", name: "Nội tại Maloch chuyển thành sát thương chuẩn 100%?", anleft: 1, anright: 0, star: 1},
{img: "maloch3", name: "Chiêu cuối Maloch có thể hất tung mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "maloch3", name: "Chiêu cuối Maloch tăng tốc chạy trong vùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "maloch3", name: "Chiêu cuối Maloch hồi máu đồng minh trong vùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "maloch3", name: "Chiêu cuối Maloch làm chậm mục tiêu trong vùng chiêu?", anleft: 1, anright: 0, star: 1},
{img: "maloch5", name: "Tiệc Hóa Trang là skin của Maloch?", anleft: 1, anright: 0, star: 0},
{img: "maloch6", name: "Samurai Tử Sĩ không là skin của Maloch?", anleft: 0, anright: 1, star: 0},
{img: "ngokhong1", name: "Ngộ Không là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "ngokhong1", name: "Ngộ Không là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "ngokhong6", name: "Nội tại Ngộ Không kích hoạt sau khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "ngokhong6", name: "Nội tại Ngộ Không giúp áp sát mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "ngokhong6", name: "Tăng Chí mạng khi ở cạnh Ngộ Không bởi Nội tại?", anleft: 0, anright: 1, star: 1},
{img: "ngokhong2", name: "Chiêu cuối Ngộ Không làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "ngokhong2", name: "Chiêu cuối Ngộ Không không thể tái kích hoạt?", anleft: 0, anright: 1, star: 1},
{img: "ngokhong2", name: "Chiêu cuối Ngộ Không giúp tàng hình?", anleft: 1, anright: 0, star: 1},
{img: "ngokhong2", name: "Chiêu cuối Ngộ Không giúp đồng đội tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "ngokhong4", name: "Hỏa Nhãn Kim Tinh không là skin của Ngộ Không?", anleft: 0, anright: 1, star: 0},
{img: "ngokhong5", name: "Siêu Việt là skin của Ngộ Không?", anleft: 1, anright: 0, star: 0},
{img: "kriknak1", name: "Kriknak là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "kriknak1", name: "Kriknak là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "kriknak4", name: "Nội tại Kriknak kích hoạt khi Chiêu trúng đích?", anleft: 1, anright: 0, star: 1},
{img: "kriknak4", name: "Nội tại Kriknak khiến kỹ năng tăng sát thương?", anleft: 0, anright: 1, star: 1},
{img: "kriknak2", name: "Chiêu cuối Kriknak giúp tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "kriknak2", name: "Chiêu cuối Kriknak có thể tái kích hoạt?", anleft: 1, anright: 0, star: 1},
{img: "kriknak2", name: "Chiêu cuối Kriknak giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "kriknak2", name: "Chiêu cuối Kriknak có thể kết hợp cùng Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "kriknak2", name: "Chiêu cuối Kriknak gây sát thương đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "kriknak2", name: "Có thể đánh thường khi Kriknak dùng Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "kriknak5", name: "Yêu Trùng Cổ Mộ không là skin của Kriknak?", anleft: 0, anright: 1, star: 0},
{img: "arthur5", name: "Arthur là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "arthur5", name: "Arthur là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "arthur5", name: "Arthur là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "arthur6", name: "Nội tại Arthur giúp tự thân tăng giáp?", anleft: 1, anright: 0, star: 1},
{img: "arthur6", name: "Nội tại Arthur giúp tăng giáp đồng đội cạnh bên?", anleft: 0, anright: 1, star: 1},
{img: "arthur6", name: "Nội tại Arthur tăng giáp theo lượng máu mất đi?", anleft: 0, anright: 1, star: 1},
{img: "arthur2", name: "Chiêu cuối Arthur có thể hất văng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "arthur2", name: "Chiêu cuối Arthur làm chậm mục tiêu trong vùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "arthur2", name: "Chiêu cuối Arthur sát thương đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "arthur3", name: "Lãnh Chúa Xương không là skin của Arthur?", anleft: 0, anright: 1, star: 0},
{img: "arthur4", name: "Hoàng Kim Cốt là skin của Arthur?", anleft: 1, anright: 0, star: 0},
{img: "slimz1", name: "Slimz là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "slimz1", name: "Slimz là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "slimz6", name: "Nội tại Slimz kích hoạt ở đòn đánh thứ 3?", anleft: 1, anright: 0, star: 1},
{img: "slimz6", name: "Nội tại Slimz xuyên thủng xung quanh mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "slimz6", name: "Nội tại Slimz giúp Chiêu khác tăng sát thương?", anleft: 0, anright: 1, star: 1},
{img: "slimz2", name: "Chiêu cuối Slimz giúp tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "slimz2", name: "Chiêu cuối Slimz giúp tăng tốc đánh?", anleft: 0, anright: 1, star: 1},
{img: "slimz2", name: "Chiêu cuối Slimz giúp tăng sát thương đòn đánh?", anleft: 1, anright: 0, star: 1},
{img: "slimz2", name: "Chiêu cuối Slimz giúp tăng sát thương kỹ năng?", anleft: 0, anright: 1, star: 1},
{img: "slimz2", name: "Chiêu cuối Slimz có tên là Thuốc cà chua?", anleft: 0, anright: 1, star: 1},
{img: "slimz5", name: "Hiệp Sĩ Thỏ Ngọc không là skin của Slimz?", anleft: 0, anright: 1, star: 0},
{img: "ilumia1", name: "Ilumia là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "ilumia1", name: "Ilumia là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "ilumia4", name: "Nội tại Ilumia giúp cường hóa Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "ilumia4", name: "Nội tại Ilumia kích hoạt khi đánh thường 2 lần?", anleft: 0, anright: 1, star: 1},
{img: "ilumia2", name: "Chiêu cuối Ilumia làm lộ diện tất cả địch?", anleft: 1, anright: 0, star: 1},
{img: "ilumia2", name: "Chiêu cuối Ilumia gây sát thương mục tiêu đầu tiên?", anleft: 0, anright: 1, star: 1},
{img: "ilumia2", name: "Chiêu cuối Ilumia khiến địch không thể thoát thân?", anleft: 0, anright: 1, star: 1},
{img: "ilumia2", name: "Chiêu cuối Ilumia kích hoạt khiến cô bất động?", anleft: 0, anright: 1, star: 1},
{img: "ilumia2", name: "Chiêu cuối Ilumia làm choáng địch trúng phải?", anleft: 1, anright: 0, star: 1},
{img: "preyta1", name: "Preyta là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "preyta1", name: "Preyta là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "preyta2", name: "Chiêu cuối Preyta giúp cường hóa Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "preyta2", name: "Chiêu cuối Preyta tạo lá chắn cho đồng đội cạnh bên?", anleft: 0, anright: 1, star: 1},
{img: "preyta2", name: "Chiêu cuối Preyta giúp đánh thường giảm tốc chạy của địch?", anleft: 0, anright: 1, star: 1},
{img: "preyta2", name: "Chiêu cuối Preyta giúp tăng tốc chạy và tốc đánh?", anleft: 1, anright: 0, star: 1},
{img: "preyta3", name: "Băng Hỏa Long Sư không là skin của Preyta?", anleft: 0, anright: 1, star: 0},
{img: "skud1", name: "Skud là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "skud1", name: "Skud là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "skud1", name: "Skud là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "skud3", name: "Nội tại Skud kích hoạt nhận cú đấm Đặc biệt?", anleft: 1, anright: 0, star: 1},
{img: "skud3", name: "Nội tại Skud giảm thời gian hồi sau khi dùng Chiêu?", anleft: 0, anright: 1, star: 1},
{img: "skud2", name: "Chiêu cuối Skud có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "skud2", name: "Chiêu cuối Skud hất văng mục tiêu lân cận?", anleft: 1, anright: 0, star: 1},
{img: "skud2", name: "Chiêu cuối Skud giúp làm mới Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "skud2", name: "Chiêu cuối Skud giúp miễn choáng đồng đội cạnh bên?", anleft: 0, anright: 1, star: 1},
{img: "raz1", name: "Raz là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "raz1", name: "Raz là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "raz2", name: "Giảm tốc chạy khi trúng Cú Đấm Chân Không của Raz?", anleft: 1, anright: 0, star: 1},
{img: "raz2", name: "Raz tăng giáp phép khi Cú Đấm Chân Không trúng đích?", anleft: 0, anright: 1, star: 1},
{img: "raz4", name: "Chiêu cuối Raz không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "raz4", name: "Chiêu cuối Raz đẩy lùi tất cả địch trúng Chiêu?", anleft: 1, anright: 0, star: 1},
{img: "raz3", name: "Băng Quyền Quán Quân là skin của Raz?", anleft: 1, anright: 0, star: 0},
{img: "raz6", name: "Chiến Thần Muay Thái không skin của Raz?", anleft: 0, anright: 1, star: 0},
{img: "lauriel1", name: "Lauriel là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "lauriel1", name: "Lauriel là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "lauriel4", name: "Nội tại Lauriel bùng nổ khi tích 4 lần Dấu ấn?", anleft: 1, anright: 0, star: 1},
{img: "lauriel4", name: "Nội tại Lauriel tích Dấu ấn lên đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "lauriel4", name: "Nội tại Lauriel kích hoạt giúp cô tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "lauriel4", name: "Nội tại Lauriel khắc Dấu ấn khi đánh thường?", anleft: 0, anright: 1, star: 1},
{img: "lauriel3", name: "Vùng Chiêu cuối Lauriel giúp giảm hồi Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "lauriel3", name: "Vùng Chiêu cuối Lauriel giúp đồng đội tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "lauriel3", name: "Vùng Chiêu cuối Lauriel giảm tốc chạy mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "lauriel5", name: "Phù Thủy Bí Ngô không là skin của Lauriel?", anleft: 0, anright: 1, star: 0},
{img: "lauriel6", name: "Hỏa Phượng Hoàng là skin của Lauriel?", anleft: 1, anright: 0, star: 0},
{img: "lauriel2", name: "Đôi Cánh Thuần Khiết giúp Lauriel vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "batman1", name: "Batman là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "batman1", name: "Batman là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "batman3", name: "Phi Tiêu Dơi của Batman giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "batman3", name: "Batman khắc Phi Tiêu Dơi lên mục tiêu đầu tiên?", anleft: 0, anright: 1, star: 1},
{img: "batman3", name: "Batman có thể làm choáng mục tiêu bởi Phi Tiêu Dơi?", anleft: 1, anright: 0, star: 1},
{img: "batman3", name: "Batman có thể hồi máu khi Phi Tiêu Dơi tự mất đi?", anleft: 0, anright: 1, star: 1},
{img: "batman2", name: "Batman tàng hình sau khi bật Chiêu cuối?", anleft: 0, anright: 1, star: 1},
{img: "batman2", name: "Batman lập tức lộ diện khi tiến gần mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "batman2", name: "Batman tấn công mục tiêu khi tái kích hoạt Chiêu cuối?", anleft: 1, anright: 0, star: 1},
{img: "batman2", name: "Không có dấu hiệu nhận biết Batman đang cạnh bên?", anleft: 0, anright: 1, star: 1},
{img: "batman2", name: "Khi lộ diện giúp Batman tăng nhiều tốc đánh?", anleft: 1, anright: 0, star: 1},
{img: "batman4", name: "Dơi Địa Ngục không là skin của Batman?", anleft: 0, anright: 1, star: 0},
{img: "airi1", name: "Airi là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "airi1", name: "Airi là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "airi5", name: "Airi có thể lướt tối đa 4 lần với Kiếm Vũ?", anleft: 0, anright: 1, star: 1},
{img: "airi5", name: "Kiếm Vũ giúp Airi vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "airi5", name: "Kiếm Vũ Airi không gây sát thương?", anleft: 0, anright: 1, star: 1},
{img: "airi2", name: "Chiêu cuối giúp Airi tạo lớp lá chắn?", anleft: 1, anright: 0, star: 1},
{img: "airi2", name: "Chiêu cuối Airi gây sát thương đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "airi2", name: "Chiêu cuối Airi có thể làm choáng?", anleft: 1, anright: 0, star: 1},
{img: "airi2", name: "Chiêu cuối Airi giúp cô tăng mạnh tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "airi2", name: "Chiêu cuối Airi luôn tạo lá chắn?", anleft: 0, anright: 1, star: 1},
{img: "airi3", name: "Cấm Vệ Nguyệt Tộc là skin của Airi?", anleft: 1, anright: 0, star: 0},
{img: "airi4", name: "Kiemono không là skin của Airi?", anleft: 0, anright: 1, star: 0},
{img: "zuka1", name: "Zuka là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "zuka1", name: "Zuka là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "zuka4", name: "Loạn Đã Bổng giúp Zuka lướt 2 lượt?", anleft: 1, anright: 0, star: 1},
{img: "zuka4", name: "Loạn Đã Bổng Zuka không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "zuka4", name: "Phi Thân Kích Zuka làm choáng khi trúng mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "zuka4", name: "Phi Thân Kích Zuka giúp tạo lá chắn?", anleft: 1, anright: 0, star: 1},
{img: "zuka4", name: "Phi Thân Kích Zuka có thể vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "zuka2", name: "Chiêu cuối Zuka làm choáng đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "zuka2", name: "Chiêu cuối Zuka không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "zuka2", name: "Chiêu cuối Zuka cường hóa đòn đánh kế?", anleft: 1, anright: 0, star: 1},
{img: "zuka5", name: "Giáo Sư Sừng Sỏ là skin của Zuka?", anleft: 1, anright: 0, star: 0},
{img: "zuka6", name: "Gấu Nhồi Bông không là skin của Zuka?", anleft: 0, anright: 1, star: 0},
{img: "ignis1", name: "Ignis là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "ignis1", name: "Ignis là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "ignis3", name: "Nội tại Ignis khắc dấu Hỏa hồn trên đòn đánh?", anleft: 0, anright: 1, star: 1},
{img: "ignis3", name: "Nội tại Ignis có thể giúp hồi máu?", anleft: 1, anright: 0, star: 1},
{img: "ignis2", name: "Chiêu cuối Ignis lập tức kích hoạt sau khi bật?", anleft: 0, anright: 1, star: 1},
{img: "ignis2", name: "Chiêu cuối Ignis có thể khắc dấu Hỏa hồn?", anleft: 1, anright: 0, star: 1},
{img: "ignis2", name: "Vùng Chiêu cuối Ignis làm chậm tốc chạy mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "murad1", name: "Murad là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "murad1", name: "Murad là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "murad8", name: "Nội tại Murad giúp mở phong ấn Chiêu cuối?", anleft: 1, anright: 0, star: 1},
{img: "murad8", name: "Nội tại Murad kích hoạt ở đòn đánh thứ 3?", anleft: 0, anright: 1, star: 1},
{img: "murad8", name: "Nội tại Murad không thể mất sau khi kích hoạt?", anleft: 0, anright: 1, star: 1},
{img: "murad4", name: "Tàn Ảnh Đao Murad có thể dùng 3 lần?", anleft: 1, anright: 0, star: 1},
{img: "murad4", name: "Tàn Ảnh Đao Murad có thể làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "murad4", name: "Tàn Ảnh Đao Murad quay lại ở lần dùng thứ 2?", anleft: 0, anright: 1, star: 1},
{img: "murad3", name: "Vô Ảnh Cực Murad có thể làm chậm mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "murad3", name: "Vô Ảnh Cực Murad không gây sát thương mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "murad3", name: "Vô Ảnh Cực giúp Murad không bị tấn công?", anleft: 1, anright: 0, star: 1},
{img: "murad2", name: "Chiêu cuối Murad tấn công đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "murad2", name: "Chiêu cuối Murad có 5 lần gây sát thương?", anleft: 1, anright: 0, star: 1},
{img: "murad2", name: "Chiêu cuối Murad thời gian hồi chiêu rất ít?", anleft: 0, anright: 1, star: 1},
{img: "murad2", name: "Chiêu cuối giúp Murad không thể bị tấn công?", anleft: 1, anright: 0, star: 1},
{img: "murad6", name: "Thiên Tài Sân Cỏ không là skin của Murad?", anleft: 0, anright: 1, star: 0},
{img: "murad5", name: "M-TP Thần Tượng Học Đường là skin của Murad?", anleft: 1, anright: 0, star: 0},
{img: "murad7", name: "Murad không có skin Siêu Việt?", anleft: 0, anright: 1, star: 0},
{img: "zill1", name: "Zill là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "zill1", name: "Zill là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "zill3", name: "Nội tại Zill tích dấu ấn bởi các đòn đánh?", anleft: 0, anright: 1, star: 1},
{img: "zill3", name: "Nội tại Zill có thể làm mới Chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "zill3", name: "Nội tại Zill tích lũy tối đa 4 dấu ấn?", anleft: 0, anright: 1, star: 1},
{img: "zill2", name: "Chiêu cuối Zill có thể tấn công nhiều mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "zill2", name: "Chiêu cuối Zill có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "zill2", name: "Chiêu cuối Zill có 5 lần gây sát thương?", anleft: 1, anright: 0, star: 1},
{img: "zill4", name: "Zill không có skin Dung Nham?", anleft: 0, anright: 1, star: 0},
{img: "arduin1", name: "Arduin là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "arduin1", name: "Arduin là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "arduin1", name: "Arduin là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "arduin3", name: "Hồn Trảm Arduin có thể làm chậm mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "arduin3", name: "Hồn Trảm Arduin hất tung đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "arduin3", name: "Hồn Trảm Arduin có thể tái kích hoạt?", anleft: 1, anright: 0, star: 1},
{img: "arduin2", name: "Chiêu cuối Arduin không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "arduin2", name: "Chiêu cuối Arduin có thể làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "arduin2", name: "Chiêu cuối Arduin kéo mục tiêu đến gần bản thân?", anleft: 0, anright: 1, star: 1},
{img: "arduin2", name: "Chiêu cuối Arduin choáng tất cả mục tiêu trúng phải?", anleft: 0, anright: 1, star: 1},
{img: "joker1", name: "Joker là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "joker1", name: "Joker là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "joker1", name: "Joker là một Trợ thủ?", anleft: 0, anright: 1, star: 0},
{img: "joker3", name: "Nội tại Joker kích hoạt sau khi dùng Chiêu?", anleft: 0, anright: 1, star: 1},
{img: "joker3", name: "Nội tại giúp Joker tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "joker3", name: "Nội tại Joker giúp giảm mạnh tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "joker2", name: "Chiêu cuối Joker có thể miễn nhiễm khống chế?", anleft: 1, anright: 0, star: 1},
{img: "joker2", name: "Chiêu cuối Joker không thể dùng lên quái?", anleft: 0, anright: 1, star: 1},
{img: "joker2", name: "Chiêu cuối Joker sát thương nhiều mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "joker2", name: "Chiêu cuối Joker giảm mạnh tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "joker2", name: "Chiêu cuối Joker có thể dùng vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "joker4", name: "Vua Hề không là skin của Joker?", anleft: 0, anright: 1, star: 0},
{img: "ryoma1", name: "Ryoma là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "ryoma1", name: "Ryoma là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "ryoma3", name: "Nhất Kích Tất Sát Ryoma choáng đơn mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "ryoma4", name: "Thần Hành Bách Biến Ryoma không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "ryoma2", name: "Chiêu cuối giúp Ryoma hồi máu?", anleft: 1, anright: 0, star: 1},
{img: "ryoma2", name: "Chiêu cuối Ryoma có 5 lần gây sát thương?", anleft: 0, anright: 1, star: 1},
{img: "ryoma5", name: "Đại Tướng Nguyệt Tộc là skin của Ryoma?", anleft: 1, anright: 0, star: 0},
{img: "astrid1", name: "Astrid là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "astrid1", name: "Astrid là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "astrid1", name: "Astrid là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "astrid3", name: "Quả Cảm Astrid giúp cường hóa đòn đánh thường?", anleft: 1, anright: 0, star: 1},
{img: "astrid3", name: "Quả Cảm Astrid không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "astrid2", name: "Chiêu cuối giúp Astrid miễn nhiễm sát thương?", anleft: 1, anright: 0, star: 1},
{img: "astrid2", name: "Astrid có thể hủy Chiêu cuối khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "astrid2", name: "Chiêu cuối Astrid làm choáng mục tiêu thấp máu?", anleft: 0, anright: 1, star: 1},
{img: "astrid4", name: "Astrid không có skin Siêu Sao Bóng Chày?", anleft: 0, anright: 1, star: 0},
{img: "telannas1", name: "Tel'Annas là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "telannas1", name: "Tel'Annas là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "telannas3", name: "Ưng Nhãn Tel'Annas duy nhất tăng mạnh tầm đánh?", anleft: 0, anright: 1, star: 1},
{img: "telannas3", name: "Ưng Nhãn giúp Tel'Annas cường hóa đòn đánh thường?", anleft: 1, anright: 0, star: 1},
{img: "telannas2", name: "Chiêu cuối Tel'Annas có thể bắn xuyên bản đồ?", anleft: 0, anright: 1, star: 1},
{img: "telannas2", name: "Chiêu cuối Tel'Annas có thể làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "telannas2", name: "Chiêu cuối Tel'Annas gây sát thương đa mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "telannas2", name: "Chiêu cuối giúp Tel'Annas tăng tốc đánh?", anleft: 0, anright: 1, star: 1},
{img: "telannas4", name: "Chung Tình Tiễn không là skin của Tel'Annas?", anleft: 0, anright: 1, star: 0},
{img: "telannas5", name: "Giám Thị Thân Thiện là skin của Tel'Annas?", anleft: 1, anright: 0, star: 0},
{img: "telannas6", name: "Tel'Annas không có skin Thánh Nữ Mật Hội?", anleft: 0, anright: 1, star: 0},
{img: "superman1", name: "Superman là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "superman1", name: "Superman là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "superman1", name: "Superman là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "superman3", name: "Nội tại giúp Superman có thêm cách di chuyển?", anleft: 1, anright: 0, star: 1},
{img: "superman3", name: "Nội tại Superman kích hoạt khi dùng Chiêu thức?", anleft: 0, anright: 1, star: 1},
{img: "superman3", name: "Nội tại Superman chỉ mất khi không di chuyển?", anleft: 0, anright: 1, star: 1},
{img: "superman2", name: "Siêu Năng Lực Superman giúp làm choáng mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "superman2", name: "Siêu Năng Lực Superman bắn laze khi đang bay?", anleft: 1, anright: 0, star: 1},
{img: "superman5", name: "Superman có skin Bất Công Lý?", anleft: 1, anright: 0, star: 0},
{img: "wonderwoman1", name: "Wonder Woman là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "wonderwoman1", name: "Wonder Woman là một Đỡ đòn?", anleft: 0, anright: 1, star: 0},
{img: "wonderwoman5", name: "Nội tại Wonder Woman phóng khiên sau 3 đòn đánh?", anleft: 0, anright: 1, star: 1},
{img: "wonderwoman5", name: "Nội tại Wonder Woman giúp giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "wonderwoman3", name: "Chiêu Dây Thừng Wonder Woman luôn kéo mục tiêu về cô?", anleft: 0, anright: 1, star: 1},
{img: "wonderwoman3", name: "Chiêu Dây Thừng Wonder Woman giúp cô vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "wonderwoman2", name: "Chiêu cuối Wonder Woman làm choáng đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "wonderwoman2", name: "Chiêu cuối Wonder Woman tạo lá chắn đồng đội phía trước?", anleft: 0, anright: 1, star: 1},
{img: "wonderwoman2", name: "Chiêu cuối Wonder Woman giúp đồng minh tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "wonderwoman6", name: "Wonder Woman không có skin Thế Chiến?", anleft: 0, anright: 1, star: 0},
{img: "xeniel1", name: "Xeniel là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "xeniel1", name: "Xeniel là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "xeniel1", name: "Xeniel là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "xeniel4", name: "Chùy Thần Lực Xeniel không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "xeniel4", name: "Chùy Thần Lực Xeniel hất tung nhiều mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "xeniel4", name: "Chùy Thần Lực Xeniel làm choáng đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "xeniel2", name: "Chiêu cuối Xeniel chỉ dùng cho đồng minh thấp máu?", anleft: 0, anright: 1, star: 1},
{img: "xeniel2", name: "Chiêu cuối Xeniel chọn kẻ địch làm mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "xeniel2", name: "Chiêu cuối Xeniel giúp đồng minh hồi máu?", anleft: 1, anright: 0, star: 1},
{img: "xeniel2", name: "Chiêu cuối giúp Xeniel tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "xeniel2", name: "Chiêu cuối giúp riêng Xeniel miễn thương?", anleft: 0, anright: 1, star: 1},
{img: "xeniel3", name: "Trung Vệ Thép là skin của Xeniel?", anleft: 1, anright: 0, star: 0},
{img: "kilgroth1", name: "Kil'Groth là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "kilgroth1", name: "Kil'Groth là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "kilgroth4", name: "Sóng Tử Vong Kil'Groth không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "kilgroth4", name: "Sóng Tử Vong Kil'Groth giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "kilgroth2", name: "Chiêu cuối giúp Kil'Groth tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "kilgroth2", name: "Chiêu cuối giúp Kil'Groth miễn thương?", anleft: 0, anright: 1, star: 1},
{img: "kilgroth2", name: "Chiêu cuối giúp Kil'Groth miễn khống chế tức thời?", anleft: 0, anright: 1, star: 1},
{img: "kilgroth3", name: "Kil'Groth có skin Quang Vinh?", anleft: 1, anright: 0, star: 0},
{img: "moren1", name: "Moren là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "moren1", name: "Moren là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "moren4", name: "Nội tại Moren kích hoạt khi đủ 4 dấu ấn?", anleft: 0, anright: 1, star: 1},
{img: "moren4", name: "Nội tại Moren kích hoạt giúp hồi lại chiêu khác?", anleft: 1, anright: 0, star: 1},
{img: "moren4", name: "Nội tại Moren duy nhất tích dấu ấn trên đòn đánh?", anleft: 0, anright: 1, star: 1},
{img: "moren3", name: "Súng Thần Công Moren bắn được 2 viên đạn?", anleft: 1, anright: 0, star: 1},
{img: "moren3", name: "Súng Thần Công giúp Moren tăng tốc đánh?", anleft: 0, anright: 1, star: 1},
{img: "moren3", name: "Súng Thần Công Moren buộc làm mới khi xong hồi chiêu?", anleft: 0, anright: 1, star: 1},
{img: "moren2", name: "Chiêu cuối Moren có thể làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "moren2", name: "Vùng chiêu cuối Moren giúp đồng minh tăng tốc chạy?", anleft: 0, anright: 1, star: 1},
{img: "moren2", name: "Vùng chiêu cuối Moren giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "teemee1", name: "TeeMee là một Trợ thủ?", anleft: 1, anright: 0, star: 0},
{img: "teemee1", name: "TeeMee là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "teemee1", name: "TeeMee là một Pháp sư?", anleft: 0, anright: 1, star: 0},
{img: "teemee4", name: "Nội tại TeeMee giúp đồng đội nhận thêm vàng?", anleft: 1, anright: 0, star: 1},
{img: "teemee4", name: "Nội tại TeeMee nhận thêm vàng khi hạ tướng địch?", anleft: 0, anright: 1, star: 1},
{img: "teemee3", name: "Rắm Thần Lực TeeMee kích hoạt sau khi dùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "teemee3", name: "Rắm Thần Lực giúp TeeMee tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "teemee3", name: "Rắm Thần Lực TeeMee có thể làm choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "teemee5", name: "Giáo Móc TeeMee không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "teemee5", name: "Giáo Móc giúp kéo mục tiêu về TeeMee?", anleft: 0, anright: 1, star: 1},
{img: "teemee5", name: "Giáo Móc TeeMee có thể làm choáng?", anleft: 1, anright: 0, star: 1},
{img: "teemee2", name: "Chiêu cuối TeeMee giúp hồi sinh đồng minh?", anleft: 1, anright: 0, star: 1},
{img: "teemee2", name: "Chiêu cuối TeeMee có thể hồi sinh nhiều mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "teemee2", name: "Chiêu cuối không thể hồi sinh cho TeeMee?", anleft: 0, anright: 1, star: 1},
{img: "teemee2", name: "Chiêu cuối TeeMee giúp hồi sinh sau khi dùng?", anleft: 0, anright: 1, star: 1},
{img: "teemee2", name: "Chiêu cuối TeeMee có thể giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "lindis1", name: "Lindis là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "lindis1", name: "Lindis là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "lindis4", name: "Nội tại Lindis kích hoạt sau khi dùng chiêu?", anleft: 0, anright: 1, star: 1},
{img: "lindis4", name: "Nội tại giúp Lindis tăng tốc chạy?", anleft: 1, anright: 0, star: 1},
{img: "lindis4", name: "Nội tại giúp Lindis bắn 2 lần trên đòn đánh?", anleft: 1, anright: 0, star: 1},
{img: "lindis5", name: "Nguyệt Quang Lindis phát hiện mục tiêu trong bụi?", anleft: 1, anright: 0, star: 1},
{img: "lindis5", name: "Nguyệt Quang Lindis không thấy mục tiêu tàng hình?", anleft: 0, anright: 1, star: 1},
{img: "lindis5", name: "Nguyệt Quang Lindis tích tối đa 4 dấu ấn?", anleft: 0, anright: 1, star: 1},
{img: "lindis2", name: "Nguyệt Vực Lindis dự trữ tối đa 3 bẫy?", anleft: 0, anright: 1, star: 1},
{img: "lindis2", name: "Nguyệt Vực Lindis có thể giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "lindis2", name: "Nguyệt Vực Lindis có thể làm lộ diện mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "lindis6", name: "Chiêu cuối Lindis dự trữ tối đa 6 ảnh ảo?", anleft: 0, anright: 1, star: 1},
{img: "lindis6", name: "Chiêu cuối Lindis không thời gian hồi?", anleft: 0, anright: 1, star: 1},
{img: "lindis3", name: "Quang Thánh Tiễn không là skin của Lindis?", anleft: 0, anright: 1, star: 0},
{img: "omen1", name: "Omen là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "omen1", name: "Omen là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "omen3", name: "Sát Niệm giúp Omen tăng tốc đánh?", anleft: 0, anright: 1, star: 1},
{img: "omen3", name: "Sát Niệm Omen có thể phản sát thương?", anleft: 1, anright: 0, star: 1},
{img: "omen3", name: "Sát Niệm Omen có thể làm chậm mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "omen3", name: "Sát Niệm Omen có thể miễn khống chế?", anleft: 0, anright: 1, star: 1},
{img: "omen2", name: "Chiêu cuối Omen có thể khóa nhiều mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "omen2", name: "Chiêu cuối biến mất khi Omen ra khỏi vùng?", anleft: 0, anright: 1, star: 1},
{img: "omen2", name: "Không thể Tốc biến khỏi vùng Chiêu cuối Omen?", anleft: 1, anright: 0, star: 1},
{img: "omen4", name: "Omen có skin Ám Tử Đao?", anleft: 1, anright: 0, star: 0},
{img: "tulen1", name: "Tulen là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "tulen1", name: "Tulen là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "tulen6", name: "Nội tại Tulen kích hoạt khi có 4 dấu ấn?", anleft: 0, anright: 1, star: 1},
{img: "tulen6", name: "Nội tại Tulen tạo ra 5 luồng sét?", anleft: 1, anright: 0, star: 1},
{img: "tulen6", name: "Nội tại Tulen không gây sát thương lên quái?", anleft: 0, anright: 1, star: 1},
{img: "tulen3", name: "Lôi Động Tulen tích lũy tối đa 3 lần?", anleft: 1, anright: 0, star: 1},
{img: "tulen3", name: "Lôi Động Tulen không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "tulen3", name: "Lôi Động Tulen có thể làm chậm mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "tulen2", name: "Chiêu cuối Tulen trúng đích kích hoạt Nội tại?", anleft: 0, anright: 1, star: 1},
{img: "tulen2", name: "Chiêu cuối Tulen không gây sát thương lên quái?", anleft: 0, anright: 1, star: 1},
{img: "tulen2", name: "Có thể cản Chiêu cuối Tulen?", anleft: 1, anright: 0, star: 1},
{img: "tulen4", name: "Tân Thần Thiên Hà là skin của Tulen?", anleft: 1, anright: 0, star: 0},
{img: "tulen5", name: "Phù Thủy Kiến Tạo không là skin của Tulen?", anleft: 0, anright: 1, star: 0},
{img: "liliana1", name: "Liliana là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "liliana1", name: "Liliana là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "liliana2", name: "Chiêu cuối Liliana làm giảm tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "liliana2", name: "Chiêu cuối Liliana có thể vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "liliana2", name: "Chiêu cuối Liliana không gây sát thương?", anleft: 0, anright: 1, star: 1},
{img: "liliana2", name: "Chiêu cuối Liliana không có thời gian hồi?", anleft: 0, anright: 1, star: 1},
{img: "liliana3", name: "Liliana có skin Thần Tượng Âm Nhạc?", anleft: 1, anright: 0, star: 0},
{img: "liliana4", name: "Nguyệt Mị Ly không là skin của Liliana?", anleft: 0, anright: 1, star: 0},
{img: "max1", name: "Max là một Đấu sĩ?", anleft: 1, anright: 0, star: 0},
{img: "max1", name: "Max là một Đỡ đòn?", anleft: 1, anright: 0, star: 0},
{img: "max1", name: "Max là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "max4", name: "Động Cơ Cao Thế Max có thể vượt địa hình?", anleft: 1, anright: 0, star: 1},
{img: "max4", name: "Động Cơ Cao Thế giúp Max tạo lá chắn?", anleft: 0, anright: 1, star: 1},
{img: "max4", name: "Động Cơ Cao Thế Max có thể choáng mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "max2", name: "Chiêu cuối Max có thể chọn đồng minh?", anleft: 0, anright: 1, star: 1},
{img: "max2", name: "Chiêu cuối Max không thể hủy khi đang bay?", anleft: 0, anright: 1, star: 1},
{img: "max2", name: "Chiêu cuối Max có thể bay xuyên bản đồ?", anleft: 1, anright: 0, star: 1},
{img: "max3", name: "Găng Tay Vàng là skin của Max?", anleft: 1, anright: 0, star: 0},
{img: "theflash1", name: "Flash là một Pháp sư?", anleft: 1, anright: 0, star: 0},
{img: "theflash1", name: "Flash là một Sát thủ?", anleft: 1, anright: 0, star: 0},
{img: "theflash3", name: "Hành Trình Siêu Tốc Flash không thể vượt địa hình?", anleft: 0, anright: 1, star: 1},
{img: "theflash3", name: "Hành Trình Siêu Tốc Flash có thể tái kích hoạt?", anleft: 1, anright: 0, star: 1},
{img: "theflash3", name: "Hành Trình Siêu Tốc Flash không gây sát thương?", anleft: 0, anright: 1, star: 1},
{img: "theflash2", name: "Chiêu cuối giúp Flash không thể bị chọn?", anleft: 1, anright: 0, star: 1},
{img: "theflash2", name: "Chiêu cuối Flash có thể hủy khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "theflash2", name: "Chiêu cuối Flash hút đơn mục tiêu vào tâm bão?", anleft: 0, anright: 1, star: 1},
{img: "theflash2", name: "Có thể di chuyển Chiêu cuối Flash?", anleft: 1, anright: 0, star: 1},
{img: "theflash4", name: "Tia Chớp Tương Lai là skin của Flash?", anleft: 1, anright: 0, star: 0},
{img: "wisp1", name: "Wisp là một Xạ thủ?", anleft: 1, anright: 0, star: 0},
{img: "wisp1", name: "Wisp là một Sát thủ?", anleft: 0, anright: 1, star: 0},
{img: "wisp3", name: "Nội tại Wisp có thể làm chậm mục tiêu?", anleft: 1, anright: 0, star: 1},
{img: "wisp3", name: "Nội tại Wisp kích hoạt khi hạ mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "wisp3", name: "Nội tại Wisp có thể gây sát thương?", anleft: 1, anright: 0, star: 1},
{img: "wisp2", name: "Chiêu cuối Wisp có 6 đợt?", anleft: 1, anright: 0, star: 1},
{img: "wisp2", name: "Chiêu cuối Wisp không gây chí mạng?", anleft: 0, anright: 1, star: 1},
{img: "wisp2", name: "Chiêu cuối Wisp có thể di chuyển khi đang dùng?", anleft: 0, anright: 1, star: 1},
{img: "wisp2", name: "Chiêu cuối Wisp có thể hủy khi đang dùng?", anleft: 1, anright: 0, star: 1},
{img: "wisp2", name: "Chiêu cuối Wisp sát thương đơn mục tiêu?", anleft: 0, anright: 1, star: 1},
{img: "camtru", name: "Cấm Trụ có thể vô hiệu công trình?", anleft: 1, anright: 0, star: 0},
{img: "capcuu", name: "Cấp Cứu hồi máu đơn mục tiêu?", anleft: 0, anright: 1, star: 0},
{img: "capcuu", name: "Cấp Cứu có thể giúp tăng tốc chạy?", anleft: 1, anright: 0, star: 0},
{img: "gamthet", name: "Gầm Thét giúp tăng tốc đánh?", anleft: 1, anright: 0, star: 0},
{img: "gamthet", name: "Gầm Thét giúp tăng tốc chạy?", anleft: 0, anright: 1, star: 0},
{img: "giapgaia", name: "Giáp Gaia hồi máu khi gây sát thương?", anleft: 0, anright: 1, star: 0},
{img: "giaphomenh", name: "Giáp Hộ Mệnh giúp hồi sinh?", anleft: 1, anright: 0, star: 0},
{img: "giapthongkho", name: "Giáp Thống Khổ có thể phản sát thương?", anleft: 1, anright: 0, star: 0},
{img: "giapthongkho", name: "Giáp Thống Khổ phản sát thương phép?", anleft: 0, anright: 1, star: 0},
{img: "giaydumuc", name: "Giày Du Mục giúp tăng tốc đánh?", anleft: 1, anright: 0, star: 0},
{img: "giaydumuc", name: "Giày Du Mục giúp tăng sát thương?", anleft: 0, anright: 1, star: 0},
{img: "giayhermes", name: "Giày Hermes giúp tăng thêm tốc chạy?", anleft: 1, anright: 0, star: 0},
{img: "giayhove", name: "Giày Hộ Vệ giảm sát thương vật lý?", anleft: 0, anright: 1, star: 0},
{img: "giaykiencuong", name: "Giày Kiên Cường tăng giáp phép?", anleft: 1, anright: 0, star: 0},
{img: "giaykiencuong", name: "Giày Kiên Cường kháng toàn bộ hiệu ứng?", anleft: 0, anright: 1, star: 0},
{img: "giayphuthuy", name: "Giày Phù Thủy tăng sát thương phép?", anleft: 1, anright: 0, star: 0},
{img: "giayphuthuy", name: "Giày Phù Thủy giúp xuyên giáp?", anleft: 0, anright: 1, star: 0},
{img: "giaythuatsi", name: "Giày Thuật Sĩ giảm hồi chiêu?", anleft: 1, anright: 0, star: 0},
{img: "guomhientriet", name: "Gươm Hiền Triết giúp giảm giáp phép?", anleft: 1, anright: 0, star: 0},
{img: "guomsamset", name: "Gươm Sấm Sét giúp chớp giật nhiều mục tiêu?", anleft: 1, anright: 0, star: 0},
{img: "herculethinhno", name: "Hercule Thịnh Nộ có thể tạo lá chắn?", anleft: 1, anright: 0, star: 0},
{img: "herculethinhno", name: "Hercule Thịnh Nộ không gia tăng sát thương?", anleft: 0, anright: 1, star: 0},
{img: "huantruongtroy", name: "Huân Chương Troy không thể tạo lá chắn?", anleft: 0, anright: 1, star: 0},
{img: "huantruongtroy", name: "Huân Chương Troy hấp thu sát thương phép?", anleft: 1, anright: 0, star: 0},
{img: "khienhuyenthoai", name: "Khiên Huyền Thoại giảm tốc đánh mục tiêu lân cận?", anleft: 0, anright: 1, star: 0},
{img: "kiemfafnir", name: "Kiếm Fafnir sát thương trên máu mục tiêu?", anleft: 1, anright: 0, star: 0},
{img: "thanhtay", name: "Thanh Tẩy giúp hóa giải hiệu ứng?", anleft: 1, anright: 0, star: 0},
{img: "trungtri", name: "Trừng Trị gây sát thương lớn lên quái?", anleft: 1, anright: 0, star: 0},
{img: "trungtri", name: "Trừng Trị có thể dùng lên tướng?", anleft: 1, anright: 0, star: 0},
{img: "trungtri", name: "Trừng Trị không có hiệu ứng ngoài sát thương?", anleft: 0, anright: 1, star: 0},
{img: "truongbang", name: "Trượng Băng giảm tốc đánh mục tiêu?", anleft: 0, anright: 1, star: 0},
{img: "bocpha", name: "Bộc Phá gây sát thương dựa trên bản thân?", anleft: 0, anright: 1, star: 0},
{img: "bocpha", name: "Bộc Phá gây sát thương chuẩn?", anleft: 1, anright: 0, star: 0},
{img: "tocbien", name: "Tốc Biến không thể vượt địa hình?", anleft: 0, anright: 1, star: 0},
{img: "aochoangbanggia", name: "Áo Choàng Băng Giá giúp cường hóa đòn đánh?", anleft: 1, anright: 0, star: 0},
{img: "aochoangbanggia", name: "Áo Choàng Băng Giá giảm tốc độ đánh mục tiêu?", anleft: 0, anright: 1, star: 0},
{img: "aochoangthanra", name: "Áo Choàng Thần Ra sát thương mục tiêu bên cạnh?", anleft: 1, anright: 0, star: 0},
{img: "aochoangthanra", name: "Áo Choàng Thần Ra không sát thướng lên quái?", anleft: 0, anright: 1, star: 0},
{img: "cungtama", name: "Cung Tà Ma có thể kích hoạt?", anleft: 1, anright: 0, star: 0},
{img: "cungtama", name: "Cung Tà Ma có hiệu ứng hút máu mạnh?", anleft: 1, anright: 0, star: 0},
{img: "cungtama", name: "Cung Tà Ma tướng nào cũng dùng được?", anleft: 0, anright: 1, star: 0},
{img: "thuannhamthach", name: "Thuẫn Nham Thạch tự động kích hoạt?", anleft: 0, anright: 1, star: 0},
{img: "thuannhamthach", name: "Thuẫn Nham Thạch có thể tạo lá chắn?", anleft: 1, anright: 0, star: 0},
{img: "thuannhamthach", name: "Thuẫn Nham Thạch giảm lực tấn công bản thân?", anleft: 1, anright: 0, star: 0},
{img: "cauphale", name: "Cầu Pha Lê giúp không bị chọn mục tiêu?", anleft: 1, anright: 0, star: 0},
{img: "cauphale", name: "Cầu Pha Lê phong ấn mục tiêu?", anleft: 0, anright: 1, star: 0},
{img: "daotruyhon", name: "Đao Truy Hồn giảm hồi máu mục tiêu bên cạnh?", anleft: 0, anright: 1, star: 0},
{img: "lenhbaiphongthan", name: "Lệnh Bài Phong Thần có thể nhận vàng?", anleft: 1, anright: 0, star: 0},
{img: "lenhbaiphongthan", name: "Lệnh Bài Phong Thần tạo giáp nhiều mục tiêu?", anleft: 0, anright: 1, star: 0},
{img: "lenhbaiphongthan", name: "Lệnh Bài Phong Thần tăng tốc chạy mục tiêu?", anleft: 1, anright: 0, star: 0},
{img: "sachtruyhon", name: "Sách Truy Hồn giảm hồi máu mục tiêu?", anleft: 1, anright: 0, star: 0},
];